package com.tickettakeit.domain.displayinfo.dao.sql;

public class DisplayInfoSqls {
    public static final String SELECT_DISPLAY_INFO = "SELECT product.category_id, category.name AS 'category_name',product.id AS 'product_id', product.category_id, display_info.id AS 'display_info_id', product.description AS 'product_description', product.content AS 'product_content', product.event AS 'product_event', display_info.opening_hours, display_info.place_name, display_info.place_lot, display_info.place_street, display_info.tel AS 'telephone', display_info.homepage, display_info.email, display_info.create_date, display_info.modify_date FROM product JOIN display_info ON product.id = display_info.product_id JOIN category ON product.category_id = category.id WHERE display_info.id = :displayInfoId";
    public static final String SELECT_DISPLAY_INFO_IMAGE = "SELECT display_info_image.id AS 'display_info_image_id', display_info_image.display_info_id, file_info.id AS 'file_id', file_info.file_name,file_info.save_file_name, file_info.content_type, file_info.delete_flag, file_info.create_date, file_info.modify_date FROM display_info_image JOIN file_info ON display_info_image.file_id = file_info.id WHERE display_info_image.display_info_id = :displayInfoId";
    public static final String SELECT_PRODUCT_MAIN_IMAGE = "SELECT file_info.content_type, file_info.create_date, file_info.delete_flag, file_info.id AS 'file_info_id', file_info.file_name, file_info.modify_date, display_info.product_id, product_image.id AS 'product_image_id', file_info.save_file_name, product_image.type FROM display_info JOIN product_image ON product_image.product_id = display_info.product_id JOIN file_info ON product_image.file_id = file_info.id where type in('ma','et') and  display_info.id = :displayInfoId limit 0, 2";
    public static final String SELECT_PRODUCT_PRICE = "SELECT product_price.create_date, product_price.discount_rate, product_price.modify_date, product_price.price, product_price.price_type_name, product_price.product_id, product_price.id AS 'product_price_id' from product_price join display_info on display_info.product_id = product_price.product_id WHERE display_info.id = :displayInfoId";
    public static final String SELECT_COMMENTS = "SELECT reservation_user_comment.comment, reservation_user_comment.id AS 'comment_id', reservation_user_comment.create_date, reservation_user_comment.modify_date, reservation_user_comment.product_id, reservation_info.reservation_date, reservation_info.reservation_email, reservation_info.id AS 'reservation_info_id', reservation_info.reservation_name, reservation_info.reservation_name, reservation_info.reservation_tel AS 'reservation_telephone', reservation_user_comment.score FROM reservation_info JOIN reservation_user_comment ON reservation_info.id = reservation_user_comment.reservation_info_id JOIN display_info ON display_info.product_id = reservation_user_comment.product_id WHERE display_info.id = :displayInfoId order by comment_id desc";
    public static final String SELECT_AVG_SCORE = "SELECT AVG(score) FROM reservation_user_comment join display_info on reservation_user_comment.product_id = display_info.product_id WHERE display_info.id = :displayInfoId";
    public static final String SELECT_COMMENT_IMAGES = "SELECT file_info.content_type, file_info.create_date, file_info.delete_flag, reservation_user_comment_image.file_id, file_info.file_name, reservation_user_comment_image.id as 'image_id', file_info.modify_date, reservation_info.id AS 'reservation_info_id', reservation_user_comment_image.reservation_user_comment_id, file_info.save_file_name FROM reservation_info JOIN reservation_user_comment_image ON reservation_info.id = reservation_user_comment_image.reservation_info_id JOIN file_info ON file_info.id = reservation_user_comment_image.file_id WHERE reservation_user_comment_image.reservation_user_comment_id = :commentId";
}
